config/routes.rb
Rails.application.routes.draw do
  get 'searches/index'
  resources :articles
  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  MIN_LENGTH = 2
  MAX_LENGTH = 250
  validates :name, presence: true, length: { minimum: MIN_LENGTH, maximum: MAX_LENGTH }
end

app/models/search.rb
class Search < ApplicationRecord
  MIN_IP_LENGTH = 9
  MAX_IP_LENGTH = 13
  MAX_LENGTH = 255
  validates :ip_address, presence: true, length: { minimum: MIN_IP_LENGTH, maximum: MAX_IP_LENGTH }
  validates :query, presence: true, length: { minimum: 1, maximum: MAX_LENGTH }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]

  # GET /articles or /articles.json
  def index
    if params[:query].present?

      @articles = Article.where(
        'lower(name) Like ?',
        "%#{params[:query].downcase}%"
      )
      # save the search results using background task
      Search.create!(query: params[:query],
                     results_count: Article.where(
                       'lower(name) Like ?',
                       "%#{params[:query].downcase}%"
                     ).count, ip_address: request.remote_ip)
    else
      @articles = Article.all
    end
  end

  # GET /articles/1 or /articles/1.json
  def show; end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit; end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:name)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search

  def index; end

  protected

  def set_search
    # group searches by query and count them
    @limit = 100
    @time_range = 1.weeks.ago..Time.now
    @searches = Search.where(
      created_at: @time_range
    ).where(
      ip_address: request.remote_ip
    ).group(:query).limit(20).order('query asc').limit(@limit).count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p class="item">
       <%= article.name %> <%= link_to "View", article_path(article) %>
  </p>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form">
    <%= form.text_field :name, placeholder:"Add article content ...", class:"input" %>
  </div>

  <div>
    <%= form.submit class:"submit-btn"  %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<div>
  <div class="header-div">
    <h1>Articles</h1>
    <div>
      <%= link_to "New article", new_article_path, class:"submit-btn" %>
    </div>
  </div>
  <%= form_with(url: articles_path, method: "GET") do |form| %>
  <div class="form">
    <%= form.label :query, "Search articles by name:", class:"label" %>
    <%= form.text_field :query, class:"input", placeholder:"search articles..." %>
    <%= form.submit "Search", class:"submit-btn" %>
  </div>
  <% end %>
  <div id="articles">
    <% if @articles.empty? %>
    <p>No articles found</p>
    <% else %>

    <% @articles.each do |article| %>
    <p class="item">
      <%= article.name %> <%= link_to "View", article_path(article) %>
    </p>
    <%end %>
    <% end %>
  </div>

app/views/articles/new.html.erb
<h1>Add New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div class="flex">
  <%= link_to "Edit", edit_article_path(@article), class:"submit-btn" %> 

  <%= button_to "Destroy", @article, method: :delete, class:"submit-btn red-btn" %>

    <%= link_to "Go Back", articles_path , class:"submit-btn default-btn"%>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRealTimeSearch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="">
    <div class="navbar">
      <div>
        <%= link_to "Rails Real TimeSearch", root_path, class:"navbar-item" %>
      </div>
      <div>
        <%= link_to "Search Results", searches_index_path, class:"navbar-item" %>
  
      </div>
    </div>
    <div class="center-div">
      <%= yield %>
    </div>
  </body>
</html>

app/views/searches/index.html.erb
<div>
  <h1>Latest Searches</h1>
  <table>
    <thead>
      <tr>
        <th>Recent Searches</th>
        <th>Quantity</th>
      </tr>
    </thead>
    <tbody>
      <% @searches.map do |k, v| %>
      <tr>
        <td><%= k %></td>
        <td><%= v %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>